services:
  ctrip-flight-alter:
    image: ghcr.io/youyi0218/ctrip-flight-alter:latest
    container_name: ctrip-flight-alter
    restart: unless-stopped
    user: "0:0"
    working_dir: /app
    volumes:
      - ./:/app
