services:
  qunar-flight-alter:
    image: ghcr.io/youyi0218/qunar-flight-alter:latest
    container_name: qunar-flight-alter
    restart: unless-stopped
    working_dir: /data
    volumes:
      - ./data:/data
