services:
  qunar-flight-alter:
    image: ghcr.io/youyi0218/qunar-flight-alter:latest
    container_name: qunar-flight-alter
    restart: unless-stopped
    user: "0:0"
    working_dir: /app
    volumes:
      - ./:/app
